# Generated by Django 5.2.5 on 2025-08-24 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_exam_parent_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='term',
        ),
        migrations.AlterField(
            model_name='performance',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
    ]
