# Generated by Django 5.2.5 on 2025-08-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_performance_exam_alter_performance_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
