# Generated by Django 5.2.5 on 2025-08-25 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_performance_exam_remove_performance_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
